# Generated by Django 6.0.2 on 2026-02-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movements',
            new_name='StockMovements',
        ),
    ]
