# Generated by Django 6.0.2 on 2026-02-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_movements_stockmovements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockMovements',
            new_name='StockMovement',
        ),
    ]
